name: campy

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.7
    - imageio-ffmpeg
    - matplotlib

    # Linux:
    # - swig

    # Maybe useful:
    # - cudatoolkit=11.3.1
    # - cudnn=8.2.1
    # - nvidia::cuda-nvcc=11.3
    # - sleap::tensorflow=2.7.0
    # - sleap::pyside2=5.14.1
    # - pillow
    # - shapely=1.7.1
    - pip
    - pip:
        - setuptools
        - opencv-python
        - rich
        # For Basler cameras:
        # - pypylon
        - "--editable=./"
