# This beginner-level config uses the CPU (gpuID: -1) 
# to compress RGB video
# using ffmpeg's X264 codec

# Recording parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 47
recTimeInSec: 10
chunkLengthInSec: 1

# Camera parameters
numCams: 4
cameraMake: "opencv"
frameWidth: 1024
frameHeight: 768
bufferSize: 10
opencvNoProps: true  # don't set any properties (for MiniCAM)
opencvExposure: 0  # 0 = no change

# Compression parameters
gpuID: 0
gpuMake: "nvidia"
pixelFormatInput: "rgb0"
pixelFormatOutput: "rgb0"
codec: "h264"
quality: 23
# preset: "superfast"
ffmpegLogLevel: "warning"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
displayFrameRate: 10
